# Generated by Django 4.2.21 on 2025-05-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Object Detection with YOLOv5 & YOLOv8: Where’s Waldo?', max_length=255)),
                ('objective', models.TextField()),
                ('dataset_description', models.TextField()),
                ('model_training', models.TextField()),
                ('sahi_description', models.TextField()),
                ('results', models.TextField()),
                ('key_learnings', models.TextField()),
                ('technologies_used', models.CharField(max_length=500)),
                ('project_link', models.URLField(blank=True, null=True)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
