services:
  - type: web
    name: portfolio
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn portfolio.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: arthurportfolio.onrender.com
      - key: DATABASE_URL
        value: postgresql://birate:r7ojiZnnRxB4iHis3hawbmX0Qpp19cIJ@dpg-d0u4f7mmcj7s739anhjg-a/portfolio_db_hll9
      - key: CLOUDINARY_URL
        sync: false # Set this manually in the dashboard

databases:
  - name: portfolio_db
    plan: free
