# Generated by Django 4.2.21 on 2025-05-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('period', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('tasks', models.TextField(help_text='Comma-separated list of tasks (e.g., Built dashboards, Configured agents)')),
                ('tools_technologies', models.CharField(help_text='Comma-separated list of tools (e.g., Kibana, Grafana, Kafka)', max_length=500)),
                ('key_contributions', models.TextField(help_text='Comma-separated list of key contributions')),
                ('achievements', models.TextField(help_text='Comma-separated list of achievements')),
                ('technical_reflection', models.TextField()),
                ('personal_reflection', models.TextField()),
            ],
        ),
    ]
