# Generated by Django 4.2.21 on 2025-05-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Birate Kabanza Arthur', max_length=100)),
                ('title', models.CharField(default='Data-Driven Explorer with a Global Journey', max_length=150)),
                ('biography', models.TextField(help_text='Your main story, academic shift, and motivations.')),
                ('passions', models.TextField(help_text='Reading, travel, non-fiction books, etc.')),
                ('studied_in_china', models.BooleanField(default=True)),
                ('chinese_degree', models.CharField(default='Petroleum Engineering', max_length=100)),
                ('studied_in_belgium', models.BooleanField(default=True)),
                ('belgian_degree', models.CharField(default='Applied Computer Science (AI Track)', max_length=100)),
                ('belgian_institution', models.CharField(default='Thomas More University of Applied Sciences', max_length=150)),
                ('native_language', models.CharField(default='French', max_length=50)),
                ('fluent_languages', models.CharField(default='English', max_length=100)),
                ('strengths', models.TextField(help_text='Comma-separated list of strengths like discipline, reading, global mindset, etc.')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
